### ISSUE TITLE
能不能不显示窗体边框和背景

### ISSUE THREAD

**Issue by cursorkey** [pfinal-nc/wails_pf#1]
你好，时钟和看板娘效果都非常酷炫，但是有个窗体的方框，不能融入到桌面背景，一下子就low了，能不能把窗体的边框和背景透明或者不显示啊。

谢谢

**Comment by pfinal-nc** [comment]
@cursorkey  这个可以做到, 稍后我去处理一下

**Comment by pfinal-nc** [comment]
@cursorkey  go 版本的 我这边尝试了一下, 没有做到完全透明, 又另开了一个项目, 你可以看看 
[git@github.com:pfinal-nc/electron_pf.git](https://github.com/pfinal-nc/electron_pf)
